/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 StudentHat.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function StudentHat (props) {
  const { nodes, materials } = useGLTF('/StudentHat.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Fabric 128.004']} position={[1.549, 1.158, 0.993]} rotation={[-2.737, -0.195, 2.548]} scale={[-0.975, -0.421, -0.975]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['Sisal Rope.004']} position={[1.256, 1.461, 1.324]} rotation={[-1.042, -0.525, -2.008]} scale={[0.017, 2.577, 0.119]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['Sisal Rope.004']} position={[0.659, -0.586, 2.566]} rotation={[-0.025, -0.257, -1.28]} scale={[0.026, 1.315, 0.051]} />
      <mesh geometry={nodes.Icosphere004.geometry} material={materials['Fabric 128.004']} position={[1.268, 1.533, 1.218]} rotation={[0.405, 0.195, 0.593]} scale={0.074} />
      <mesh geometry={nodes.Icosphere005.geometry} material={materials['Sisal Rope.005']} position={[0.571, -0.302, 2.529]} rotation={[0.016, -0.446, 0.193]} scale={[0.08, 0.147, 0.08]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Fabric 128.005']} position={[1.329, 1.445, 1.233]} rotation={[0.393, 0.208, 0.585]} scale={[1.368, 0.048, 1.368]} />
      <mesh geometry={nodes.Icosphere007.geometry} material={materials['Sisal Rope.007']} position={[0.571, -0.302, 2.529]} rotation={[-0.053, -0.428, 0.267]} scale={[0.08, 0.147, 0.08]} />
    </group>
  )
}

useGLTF.preload('/StudentHat.gltf')
