/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 StudentHat.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function StudentHat(props) {
  const { nodes, materials } = useGLTF('/StudentHat.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.766, 0.138, 0.075]} rotation={[0, 0, 1.137]} scale={-0.057}>
        <mesh geometry={nodes.Rope.geometry} material={materials.Fabric} position={[6.342, 23.09, 1.47]} rotation={[-Math.PI / 2, -0.067, -Math.PI / 2]} scale={-0.222}>
          <mesh geometry={nodes.Tassels.geometry} material={materials.Fabric} position={[-11.034, -21.171, 55.21]} rotation={[1.647, 0.697, -1.658]} scale={54.491} />
        </mesh>
      </group>
      <mesh geometry={nodes.Cap_Cylinder.geometry} material={materials['White Powder Coating Texture']} position={[-0.03, 0.101, 0.002]} rotation={[0, 0, -0.367]} scale={[0.523, 0.23, 0.523]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['White Powder Coating Texture']} position={[0.024, 0.288, 0]} rotation={[-Math.PI, 0, -2.775]} scale={[-0.818, -13.543, -0.818]} />
      <mesh geometry={nodes.Button.geometry} material={materials.Fabric} position={[0.077, 0.426, 0]} rotation={[0, 0, -0.367]} scale={[-0.066, -0.024, -0.066]} />
    </group>
  )
}

useGLTF.preload('/StudentHat.gltf')
